export const SHOW_EMPLOYEE = 'SHOW_EMPLOYEE'
export const CREATE_EMPLOYEE = 'CREATE_EMPLOYEE'

export const SPINNER = 'EMPLOYEE_SPINNER'
export const DELETE_SPINNER = 'DELETE_EMPLOYEE_SPINNER'
export const UPDATE_SPINNER = 'UPDATE_SPINNER'

export const SAVE_EMPLOYEE = 'SAVE_EMPLOYEE'
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE'
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE'

export const SET_REMOVED_EMPLOYEE = 'SET_REMOVED_EMPLOYEE'
export const SET_UPDATE_EMPLOYEE = 'SET_UPDATE_EMPLOYEE'
